//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransServiceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllOrder
    {
        public int IdAllOrder { get; set; }
        public Nullable<int> IdCleint { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdVehicle { get; set; }
        public Nullable<int> IdTypeCargo { get; set; }
        public string NameOrder { get; set; }
        public string NameCompanyReception { get; set; }
        public string CountryReception { get; set; }
        public string PostCodeReception { get; set; }
        public string CityReception { get; set; }
        public string StreetReception { get; set; }
        public string NumberOfBuildingReception { get; set; }
        public string PhoneReception { get; set; }
        public string EmailReception { get; set; }
        public System.DateTime MaxDateReception { get; set; }
        public string DescriptionReception { get; set; }
        public string NameCompanyDelivery { get; set; }
        public string CountryDelivery { get; set; }
        public string PostCodeDelivery { get; set; }
        public string CItyDelivery { get; set; }
        public string StreetDelivery { get; set; }
        public string NumberOfBuildingDelivery { get; set; }
        public string PhoneDelivery { get; set; }
        public string EmailDelivery { get; set; }
        public System.DateTime DataMaxDelivery { get; set; }
        public string DescriptionDelivery { get; set; }
        public string LoadWeight { get; set; }
        public string Hegiht { get; set; }
        public string Width { get; set; }
        public string Depth { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateAcceptedCargo { get; set; }
        public string LastNameIssusing { get; set; }
        public string NumerWZ { get; set; }
        public string DescriptionAcceptedCargo { get; set; }
        public Nullable<System.DateTime> DataIssuseCargo { get; set; }
        public string LastNameAccepting { get; set; }
        public string NumberPZ { get; set; }
        public string DescriptionIssusingCargo { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeCargo TypeCargo { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
