//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransServiceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AllOrder = new HashSet<AllOrder>();
        }
    
        public int IdEmployee { get; set; }
        public Nullable<int> IdLogin { get; set; }
        public Nullable<int> IdEmployeeType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string NumberBuilding { get; set; }
        public string NumberApartment { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string IndentyficatorEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllOrder> AllOrder { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Login Login { get; set; }
    }
}
