//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransServiceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int IdSerwis { get; set; }
        public Nullable<int> IdVehicle { get; set; }
        public Nullable<int> IdTypeService { get; set; }
        public System.DateTime DateService { get; set; }
        public string Defects { get; set; }
        public string ReplacedParts { get; set; }
        public string DescriptionRepair { get; set; }
        public string TotalMileage { get; set; }
        public string Description { get; set; }
    
        public virtual TypeService TypeService { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
