//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransServiceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.AllOrder = new HashSet<AllOrder>();
            this.Service = new HashSet<Service>();
            this.VehicleCard = new HashSet<VehicleCard>();
        }
    
        public int IdVehicle { get; set; }
        public string Marke { get; set; }
        public string CarModel { get; set; }
        public string YearProduction { get; set; }
        public string EngineCapacity { get; set; }
        public string EquipmentVersion { get; set; }
        public string TypeBody { get; set; }
        public string RegistrationNumber { get; set; }
        public string EngineNumber { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllOrder> AllOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleCard> VehicleCard { get; set; }
    }
}
